function registry = datasetRegistry()
% datasetRegistry: THE single place that knows about every dataset this
% project can use. Added because the original plan hardcoded four
% specific datasets (APTOS/IDRiD/DRIVE/Messidor-2) directly into the
% training scripts - and in practice, only Messidor-2 actually downloaded
% (APTOS and IDRiD sit behind a Kaggle-competition-join wall and an IEEE
% DataPort account respectively; DRIVE behind a grand-challenge.org
% registration). Rather than re-hardcode a new fixed list that might hit
% the same problem, every training script now asks THIS function what's
% actually on disk and adapts - so adding a dataset back (if you get
% APTOS working later) or dropping one that stops working never requires
% touching train_UNet_Segmentation.m or the grading data loader again.
%
% OUTPUT: registry - struct array, one entry per known dataset, with:
%   .name        - short identifier
%   .purpose     - 'grading' | 'vessel_seg' | 'lesion_seg' | 'test_holdout'
%   .localDir    - where this project expects it after you extract it
%   .available   - true/false, computed by actually checking the folder
%   .sizeHint    - human-readable expectation (DISPLAY ONLY - never parsed
%                  for validation; see structured counts below)
%   .accessNote  - why this one was chosen / how to get it (prose)
%   .sourceUrl   - machine-readable source URL, or 'UNKNOWN' (populated
%                  ONLY from values already documented in accessNote -
%                  mirrors are recorded as mirrors, never as official)
%   .sourceType  - 'official' | 'mirror' | 'UNKNOWN'
%   .expectedImageCount / .expectedLabelCount / .expectedMaskCount -
%                  exact integers ONLY where this file already states an
%                  authoritative count; NaN = COUNT_NOT_VERIFIED (a range
%                  or "~" figure in sizeHint NEVER becomes a hard count)
%   .versionPolicy - how to record the release (e.g. 'download-date' or
%                  'UNKNOWN' where no release identifier is documented)
%
% Run this on its own to get a status report:
%   registry = datasetRegistry(); struct2table(registry(:))

DATA_ROOT = fullfile('data');

registry = struct('name',{}, 'purpose',{}, 'localDir',{}, 'available',{}, 'sizeHint',{}, 'accessNote',{}, ...
    'sourceUrl',{}, 'sourceType',{}, 'expectedImageCount',{}, 'expectedLabelCount',{}, 'expectedMaskCount',{}, 'versionPolicy',{});

registry(end+1) = entry('Messidor-2', 'test_holdout', fullfile(DATA_ROOT,'Messidor-2','images'), ...
    '1748 images (1744 gradable)', ...
    ['Confirmed working - adcis.net via a Kaggle mirror. Grades are NOT included in the base ' ...
     'download; get them from kaggle.com/datasets/google-brain/messidor2-dr-grades and combine ' ...
     'with buildMessidorTestSet.m / buildMessidorLabeledSet.m.'], ...
    'kaggle.com/datasets/google-brain/messidor2-dr-grades', 'mirror', 1748, NaN, NaN, 'download-date');

registry(end+1) = entry('DDR', 'grading', fullfile(DATA_ROOT,'DDR','images'), ...
    '~10,000 ICDR-graded images', ...
    ['PRIMARY grading-training recommendation. huggingface.co/datasets/ctmedtech/DDR-dataset ' ...
     '(or jerrodz/DDR-dataset - same data, different reupload). No Kaggle-competition wall. ' ...
     'Also has 757 images with pixel-level MA/HE/EX/SE masks - see DDR_seg purpose below.'], ...
    'huggingface.co/datasets/ctmedtech/DDR-dataset', 'mirror', NaN, NaN, NaN, 'download-date');

registry(end+1) = entry('DDR_seg', 'lesion_seg', fullfile(DATA_ROOT,'DDR','segmentation'), ...
    '757 images with MA/HE/EX/SE pixel masks', ...
    'Same HuggingFace source as DDR above, the pixel-annotated subset specifically.', ...
    'huggingface.co/datasets/ctmedtech/DDR-dataset', 'mirror', NaN, NaN, 757, 'download-date');

registry(end+1) = entry('DIARETDB1', 'lesion_seg', fullfile(DATA_ROOT,'DIARETDB1'), ...
    '89 images with MA/HE/EX markings', ...
    ['Backup/supplement lesion source. kaggle.com/datasets/nguyenhung1903/diaretdb1-standard-diabetic-retinopathy-database ' ...
     '- a regular Kaggle Dataset (not a Competition), so it should share Messidor-2''s low-friction ' ...
     'access rather than APTOS''s. NOTE: DIARETDB1 ships per-grader confidence markings, not clean ' ...
     'binary masks - inspect the actual files before assuming pixelLabelDatastore can read them directly.'], ...
    'kaggle.com/datasets/nguyenhung1903/diaretdb1-standard-diabetic-retinopathy-database', 'UNKNOWN', 89, NaN, NaN, 'download-date');

registry(end+1) = entry('STARE', 'vessel_seg', fullfile(DATA_ROOT,'STARE'), ...
    '20 images with vessel masks', ...
    'cecas.clemson.edu/~ahoover/stare - direct university hosting, no account needed.', ...
    'cecas.clemson.edu/~ahoover/stare', 'UNKNOWN', 20, NaN, 20, 'download-date');

registry(end+1) = entry('CHASE_DB1', 'vessel_seg', fullfile(DATA_ROOT,'CHASE_DB1'), ...
    '28 images with vessel masks', ...
    'researchinnovation.kingston.ac.uk (Kingston University) - direct hosting, no account needed.', ...
    'researchinnovation.kingston.ac.uk', 'UNKNOWN', 28, NaN, 28, 'download-date');

registry(end+1) = entry('HRF', 'vessel_seg', fullfile(DATA_ROOT,'HRF'), ...
    '45 images with vessel masks', ...
    'www5.cs.fau.de/fileadmin/research/datasets/fundus-images (FAU Erlangen) - direct hosting.', ...
    'www5.cs.fau.de/fileadmin/research/datasets/fundus-images', 'UNKNOWN', 45, NaN, 45, 'download-date');

registry(end+1) = entry('DRIVE', 'vessel_seg', fullfile(DATA_ROOT,'DRIVE'), ...
    '40 images with vessel masks', ...
    ['Original plan''s vessel-pretraining source - worth one more attempt at drive.grand-challenge.org, ' ...
     'but not depended on: STARE+CHASE_DB1+HRF alone already exceed DRIVE''s image count.'], ...
    'drive.grand-challenge.org', 'UNKNOWN', 40, NaN, 40, 'download-date');

registry(end+1) = entry('APTOS2019', 'grading', fullfile(DATA_ROOT,'APTOS2019'), ...
    '3662 ICDR-graded images', ...
    ['Original plan''s primary grading source. Sits behind Kaggle''s competition-join flow, which is ' ...
     'the likely reason it didn''t download while the Messidor-2 (a regular Dataset, not a ' ...
     'Competition) did. Not depended on now that DDR covers the same role at ~3x the size - ' ...
     'worth retrying later if you get the competition join sorted out, as free extra training data.'], ...
    'UNKNOWN', 'UNKNOWN', 3662, 3662, NaN, 'download-date');

registry(end+1) = entry('IDRiD', 'lesion_seg', fullfile(DATA_ROOT,'IDRiD'), ...
    '516 images, 81 with segmentation masks', ...
    ['Original plan''s segmentation source. Sits behind an IEEE DataPort account. Not depended on ' ...
     'now that DDR_seg (757 images) exceeds IDRiD''s segmentation subset (81 images) in size.'], ...
    'UNKNOWN', 'UNKNOWN', 516, NaN, 81, 'download-date');

for i = 1:numel(registry)
    registry(i).available = isfolder(registry(i).localDir) && ~isempty(dir(fullfile(registry(i).localDir,'*.*'))) ...
        && numel(dir(fullfile(registry(i).localDir))) > 2; % more than just . and ..
end

if nargout == 0
    fprintf('%-12s %-14s %-8s %s\n', 'NAME', 'PURPOSE', 'STATUS', 'EXPECTED AT');
    for i = 1:numel(registry)
        status = 'MISSING';
        if registry(i).available, status = 'FOUND'; end
        fprintf('%-12s %-14s %-8s %s\n', registry(i).name, registry(i).purpose, status, registry(i).localDir);
    end
end
end

function e = entry(name, purpose, localDir, sizeHint, accessNote, ...
    sourceUrl, sourceType, expectedImageCount, expectedLabelCount, expectedMaskCount, versionPolicy)
e = struct('name', name, 'purpose', purpose, 'localDir', localDir, ...
    'available', false, 'sizeHint', sizeHint, 'accessNote', accessNote, ...
    'sourceUrl', sourceUrl, 'sourceType', sourceType, ...
    'expectedImageCount', expectedImageCount, 'expectedLabelCount', expectedLabelCount, ...
    'expectedMaskCount', expectedMaskCount, 'versionPolicy', versionPolicy);
end
